admin_id = 114514
api_endpoint = "https://api.openai.com/v1"
models = [
  { prefix = "3$", model = "gpt-3.5-turbo" },
  { prefix = "o$", model = "claude-3-opus" },
  { prefix = "d$", model = "deepseek-chat" },
  { prefix = "$", model = "gpt-4" },
]
default_model = "gpu-4"
vision_model = 'gpt-4-vision-preview'
