admin_id = 114514
api_endpoints = [
  { name = "openai", url = "https://api.openai.com/v1" }
]
default_api_endpoint = "openai"

models = [
  { prefix = "3$", model = "gpt-3.5-turbo" },
  { prefix = "4$", model = "gpt-4" },
  { prefix = "4v$", model = "gpt-4-vision-preview" },
  { prefix = "d$", model = "deepseek-chat" },
  { prefix = "g$", model = "gemini-pro" },

  # the default
  { prefix = "$", model = "claude-3-opus" },
]
default_model = "claude-3-opus"
vision_model = 'gpt-4-vision-preview'
