admin_id = 114514
api_endpoints = [
  { name = "openai", url = "https://api.openai.com/v1" }
]
default_api_endpoint = "openai"

models = [
  { prefix = "o1 ", name = "o1-mini", no_system_prompt = true },

  { prefix = "$ ", name = "claude-3-opus" },

  { prefix = "t ", name = "claude-3-7-sonnet-latest", system_prompt = "The user will send you some text and optionally a language name. You need to translate it into Chinese. If the user sends a single word, you should also include some expanations and usages. Note that your answer should also in Chinese." },
]
