admin_id = 114514

# system_prompt = "Current Beijing Time: {current_time}. Reply in the same language as the user sent you."  # supports {current_time}, {model}
# default_image_prompt = "Describe the image"
# default_image_reply_prompt = "Continue"

api_endpoints = [
  { name = "openai", url = "https://api.openai.com/v1" },
  { name = "anthropic", url = "https://api.anthropic.com" },
]
default_api_endpoint = "openai"

models = [
  { prefix = "o1", name = "o1-mini", no_system_prompt = true },

  { prefix = "$", name = "claude-3-opus", endpoint = "anthropic", api_type = "anthropic" },

  { prefix = "t", name = "claude-3-7-sonnet-latest", endpoint = "anthropic", api_type = "anthropic", system_prompt = "The user will send you some text and optionally a language name. You need to translate it into Chinese. If the user sends a single word, you should also include some expanations and usages. Note that your answer should also in Chinese." },

  # inline system prompt: om,[You are a helpful bot, current time {current_time}] hello
  # escaped brackets: om,[Respond with JSON like \[1,2,3\]] hello
]
