admin_id = 114514
api_endpoints = [
  { name = "openai", url = "https://api.openai.com/v1" }
]
default_api_endpoint = "openai"

models = [
  { prefix = "3$", name = "gpt-3.5-turbo" },
  { prefix = "4$", name = "gpt-4" },
  { prefix = "4v$", name = "gpt-4-vision-preview" },
  { prefix = "d$", name = "deepseek-chat" },
  { prefix = "g$", name = "gemini-pro" },

  # the default
  { prefix = "$", name = "claude-3-opus" },
]
