version: '3'

services:
    bot:
        build: .
        volumes:
            - ./:/bot
        command: python main.py
        working_dir: /bot
        restart: always
        environment:
          - OPENAI_API_KEY=
          - TELEGRAM_BOT_TOKEN=
          - aws_access_key_id=
          - aws_secret_access_key=
          - aws_region_name=
          - GOOGLE_SEARCH_KEY=
          - GOOGLE_SEARCH_CX=
          - BING_SEARCH_V7_ENDPOINT=
          - BING_SEARCH_V7_SUBSCRIPTION_KEY=
