[project]
name = "chatgpt-telegram-bot"
version = "0.1.0"
description = ""
authors = [
    {name = "SharzyL", email = "me@sharzy.in"},
    {name = "zzh1996", email = "zhengzihan1996@gmail.com"},
]
dependencies = [
    "Telethon<2.0.0,>=1.32.0",
    "python-socks<3.0.0,>=2.4.4",
    "cryptg<1.0.0,>=0.4.0",
    "openai",
    "anthropic",
    "loguru>=0.7.2",
]
requires-python = "<4.0,>=3.11"
readme = "README.md"
license = {text = "MIT"}

[project.scripts]
chatgpt-telegram-bot = "chatgpt_telegram_bot.main:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv]
python-preference = "only-system"

[tool.ruff]
line-length = 120

[tool.ruff.format]
quote-style = "single"
